### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by michaelbukachi** [ObaraEmmanuel/Formation#1]
Hello. Nice library! Do you mind adding a TODO list on the Readme of what's pending and needs to be done?

**Comment by ObaraEmmanuel** [comment]
I will add milestone issues soon to make it easier to find ways to contribute. How familiar are you with tkinter?

**Comment by michaelbukachi** [comment]
Used it a couple of years back. Shouldn't be too hard to get re-acquinted with the toolkit.
