### ISSUE TITLE
Is there a way to change the text of the title bar?

### ISSUE THREAD

**Issue by hirokun2016** [ObaraEmmanuel/Formation#19]
Hi,
  I am trying to find a solution on how to change the text of the title bar of the main window. Is there such a way for this?

Regards,
Bryan

**Comment by ObaraEmmanuel** [comment]
@hirokun2016 This will be much easier in the new release which will be out today or tomorrow at the latest. For the older version you can change the title in your code as follows
```python
from formation import AppBuilder

builder = AppBuilder(path="somefile.xml")
builder._app.title("My title")

builder.mainloop()
```

``._app`` gives you access to the underlying toplevel window. In the new version it will be possible to change the title in the editor. Let me know if that works.

**Comment by KavyanshKhaitan2** [comment]
@ObaraEmmanuel 
This issue has been resolved.
Please close it to avoid confusion.

**Comment by KavyanshKhaitan2** [comment]
To change the text of the title bar now, follow these steps:
![image](https://github.com/ObaraEmmanuel/Formation/assets/73186427/38a3fd77-14ea-46ca-8126-4f2c4f8cc199)

**Comment by ObaraEmmanuel** [comment]
@KavyanshKhaitan2 thanks for the clear illustration.

**Comment by KavyanshKhaitan2** [comment]
> @KavyanshKhaitan2 thanks for the clear illustration.

You're welcome!
