### ISSUE TITLE
Defining variables in the variablepane causes error after re-openning the file

### ISSUE THREAD

**Issue by AliElkhatib** [ObaraEmmanuel/Formation#22]
when i try to define variables in variablepane, after saving the file and open it again, it shows an error message as shown in attached image.
![Screenshot 2023-07-21 020935](https://github.com/ObaraEmmanuel/Formation/assets/42626558/f43ed413-0a1c-49fb-82cb-5191d19e03d4)

**Your environment**
 - OS: [windows 11]
 - `formation` Version 0.6.2
 - Python version: [3.9]
 - tk version: [8.6]

but i found out that when i open xml and change the window tag from tkinter.Tk to tkinter.Frame it works fine.

**Comment by ObaraEmmanuel** [comment]
@AliElkhatib Thanks for reporting this. That is definitely a bug. I already have a fix for it so I will release a patch soon.

**Comment by ObaraEmmanuel** [comment]
@AliElkhatib this should be fixed now. If it is not let me know.
