### ISSUE TITLE
[BUG] Treeview container

### ISSUE THREAD

**Issue by milia20** [ObaraEmmanuel/Formation#28]
Hi.
I found problem with Treeview container.  In native components we have Treeview container, when i want to change attributes -> show from  base value **tree** to **headings** formation studio saves information in xml, like attr:show="('headings',)"
And this raise error

![bug](https://github.com/ObaraEmmanuel/Formation/assets/61024440/0a864f55-c3c0-48a7-9ed1-de83674db29d)

1. Place Treeview container
2. Change attributes - show from tree to headings
3. Save file

 - OS: Win 10
 - `formation` Version 0.6.3
 - Python version: 3.10.4 and 3.12
 - tk version: 8.6

After changing xml file "('headings',)" -> "headings" Works fine, error is gone.

**Comment by ObaraEmmanuel** [comment]
@milia20 thanks for using Formation. I too have encountered this issue before. I will look into it and try to get a fix.

**Comment by milia20** [comment]
Thanks for fix.
