### ISSUE TITLE
There is a similar project. Maybe the two can join forces.

### ISSUE THREAD

**Issue by mardukbp** [ObaraEmmanuel/Formation#3]
[Pygubu](https://github.com/alejandroautalan/pygubu-designer) is a GUI designer for Tkinter.

And actually both are very relevant for all languages that have Tk bindings. I have the intention to write a Kotlin/Native library to develop GUI applications with Tk and I would like to port [this DSL](https://github.com/AndyObtiva/glimmer-dsl-tk) from Ruby.

I will setup an "Awesome Tk" GitHub repo to give all these projects more visibility. Stay tuned!

**Update**: [Awesome Tk](https://github.com/mardukbp/awesome-tk) is up and running. Formation is already there. Keep up your awesome work!

**Comment by ObaraEmmanuel** [comment]
I really appreciate. I will see how we can join forces. Formation studio is still very new compared to Pygubu but has been designed to allow much more flexibility in design and extensibility. It's however still a work in progress.
