### ISSUE TITLE
[BUG] CTR+V requires deselection with multiple items

### ISSUE THREAD

**Issue by mrx23dot** [ObaraEmmanuel/Formation#37]
Select multiple items
press ctrl+c
press ctrl+v

items not copied, unless we deselect before pasting.

No deselection is needed when only one item is selected.

**Comment by ObaraEmmanuel** [comment]
@mrx23dot I have managed to reproduce the issues and will work on a fix. Thanks for bringing this up.

**Comment by ObaraEmmanuel** [comment]
This should be fixed.
