### ISSUE TITLE
[BUG] indent spaces UI bug

### ISSUE THREAD

**Issue by mrx23dot** [ObaraEmmanuel/Formation#38]
Up down buttons don't do anything 

![2024-10-31 12_14_35-Preferences](https://github.com/user-attachments/assets/f1253e45-2d35-4256-ba3a-1487e1f017e6)

**Your environment**
 - OS: Windows 
 - formation-studio-0.7.0
 - Python version:   Python 3.7.0

**Comment by ObaraEmmanuel** [comment]
Thanks for bringing this up @mrx23dot. I will try to patch the issue.

**Comment by ObaraEmmanuel** [comment]
This is fixed.
