### ISSUE TITLE
[BUG] copying checboxes links them

### ISSUE THREAD

**Issue by mrx23dot** [ObaraEmmanuel/Formation#43]
1. place a checkbutton
2. ctrl+c copy paste it
3. if you click the copied one the original one also gets set and vica versa,
![2024-10-31 13_06_20-Greenshot](https://github.com/user-attachments/assets/06cd8cad-bacb-4e38-abc5-703432e0c062)

![2024-10-31 13_06_34-Greenshot](https://github.com/user-attachments/assets/fb513f92-1f0f-4b33-b07c-4719345d13b9)

but there is no indication in Style pane that they are linked.

**Your environment**
    OS: Windows
    formation-studio-0.7.0
    Python version: Python 3.7.0

**Comment by ObaraEmmanuel** [comment]
Thanks for bringing this up @mrx23dot. I will work to fix this along with its related issue #44

**Comment by ObaraEmmanuel** [comment]
This should be fixed now.
