### ISSUE TITLE
[BUG] invalid attr:variable?

### ISSUE THREAD

**Issue by mrx23dot** [ObaraEmmanuel/Formation#44]
A simple layout like this executes on green button:,
![2024-10-31 13_23_26-Formation studio - C__apps_myApps_mSerial_testlayout xml](https://github.com/user-attachments/assets/49a158d0-520f-4da0-a43f-abff5d4f1cfe)

but when I add a checkbox, it doesn't show a preview when I press the green button.

if I remove
`attr:variable=".!frame3.!panedwindow.!panedwindow.!tabview.!designcontext.!designer.!checkbutton2" `

from xml line 
`  <tkinter.ttk.Checkbutton name="checkbutton2" attr:variable=".!frame3.!panedwindow.!panedwindow.!tabview.!designcontext.!designer.!checkbutton2" attr:text="checkbutton2" layout:width="112" layout:height="25" layout:x="99" layout:y="88" layout:bordermode="outside"/>`

it fixes the issue and shows the UI with 
`app = AppBuilder(path="testlayout.xml")`

so looks like attr:variable is invalid (without any warning)

Your environment
OS: Windows
formation-studio-0.7.0
Python version: Python 3.7.0

**Comment by ObaraEmmanuel** [comment]
Hello @mrx23dot. Thank you for you interest in Formation and raising this issue. The issues has been around for a while and I initially dismissed it as a simple annoyance but I will get round to fixing it. 

> interesting, attr:variable only created for checkbuttons, so might be related to #43

Yeah. They are definitely related and fixing one will resolve the other.

> Regarding content of frame3.!panedwindow.!panedwindow why aren't any of these items in the xml?

Those are elements belonging to the studio's UI interface and not the design file. They are supposed to be stripped from the generated XML.

> Also shouldn't there be an option for attr:variable in Attribute pane?

The option is there under `variable`.

**Comment by ObaraEmmanuel** [comment]
> Don't get me wrong, Formation is still the best editor I found for Tkinter, it's just a bit behind compared to wxPython editors. (but at least Tkinter is shipped with python)

Thanks for the commendations. The wxPython editors have been a round for longer and have a lot more people working on them.  I am just one guy but I will do my best. I believe we can improve the state of the project when issues are reported like like this. So, feel free to report as many issues as you can find or suggest features.

> Adding some warning msg to console would be great when there is something wrong in .xml layout (like invalid attr:variable), or assertion msg, currently it just exits without knowing why.

When previewing designs using the run button, they are run in a separate process so I will try to pipe the output back and display an error dialog.

**Comment by ObaraEmmanuel** [comment]
This should be fixed. @mrx23dot you can add the error reporting on preview as a separate feature request issue.
