### ISSUE TITLE
[FEATURE] periodic tasks

### ISSUE THREAD

**Issue by mrx23dot** [ObaraEmmanuel/Formation#46]
Please add a simple way to inject periodic function calls.

None of the suggested methods work with this framework
https://stackoverflow.com/questions/459083/how-do-you-run-your-own-code-alongside-tkinters-event-loop

Also couldn't find anything in doc.

And starting a side thread is only served once after I call   app.mainloop()

**Comment by ObaraEmmanuel** [comment]
This is not something that can be implemented into the framework. Formation studio only loads Tk widgets for you but the business logic and manipulation of said widgets is the responsibility of the developer.

Assuming `test.xml` has a label widget with the id `label_1`, you can perform a 2 second periodic function as follows. 

```python
from formation.loader import AppBuilder

class App(AppBuilder):

    def __init__(self):
        super().__init__(path=r"test.xml")
        self.connect_callbacks(self)
        self.count = 0
        self._app.after(2000, self._update_text)

    def _update_text(self):
        self.label_1["text"] = count
        count += 1
        self._app.after(2000, self._update_text)



if __name__ == "__main__":
    App().mainloop()
```

> Note: Tkinter might not work very well with multithreading so it is always better to stick to the `after` method.

**Comment by ObaraEmmanuel** [comment]
This just looks exactly like the code in the Stackoverflow link and is really just app business logic and has nothing to do with the framework. The only thing is the `_app` property which could be any widget in your app. You can bind `after` to any tk widget.
