### ISSUE TITLE
[BUG] Slow Fonts menu

### ISSUE THREAD

**Issue by mrx23dot** [ObaraEmmanuel/Formation#49]
Fonts drop down is painfully slow to navigate:

![image](https://github.com/user-attachments/assets/ae0546ce-6b48-4f51-8a0f-11341b23e0ef)

when pressing up/down on scrollbar

**Comment by ObaraEmmanuel** [comment]
Sadly this appears to be a side effect of some optimization added a long time ago to prevent glitching that might not be relevant now. Thanks for reporting, I will fix that.

**Comment by ObaraEmmanuel** [comment]
Noted. That would indeed be a useful feature.

**Comment by ObaraEmmanuel** [comment]
This should be fixed.
