### ISSUE TITLE
Doesn't start on windows

### ISSUE THREAD

**Issue by bubthegreat** [ObaraEmmanuel/Formation#5]
Really excited to try this out but it doesn't look like it supports windows!

```
(venv) PS C:\Users\bubth\Development\test> python --version
Python 3.8.6
(venv) PS C:\Users\bubth\Development\test> pip install formation-studio
Requirement already satisfied: formation-studio in c:\users\bubth\development\test\venv\lib\site-packages (0.2.0)
Requirement already satisfied: lxml in c:\users\bubth\development\test\venv\lib\site-packages (from formation-studio) (4.6.2)
Requirement already satisfied: pywin32 in c:\users\bubth\development\test\venv\lib\site-packages (from formation-studio) (300)
Requirement already satisfied: Pillow in c:\users\bubth\development\test\venv\lib\site-packages (from formation-studio) (8.1.2)
(venv) PS C:\Users\bubth\Development\test> formation-studio
(venv) PS C:\Users\bubth\Development\test>
```
Nothing happens after running the formation-studio command.

**Comment by bubthegreat** [comment]
Submitted a PR for this: https://github.com/ObaraEmmanuel/Formation/pull/6

**Comment by ObaraEmmanuel** [comment]
Hello, thank you for using formation. Formation studio started out from windows so it's windows support should be excellent. I have never tried it out in a virtual environment though. Let me try and get back to you in a moment

**Comment by bubthegreat** [comment]
Allright - the PR I submitted does fix this so it's not relying on any relative package directories and does fix this so it runs appropriately:
![image](https://user-images.githubusercontent.com/12198817/110230727-19700080-7ed0-11eb-9561-f72dd68d10b3.png)
Feel free to ignore if you feel like the changes aren't appropriate.

**Comment by bubthegreat** [comment]
FWIW - the way I usually test this is to run:
```
python setup.py sdist
pip install dist/<package-name>
```
Then I try and run the commands and make sure it doesn't error in a build job.

If that works for you but not for me I'd love to get you any more information that's helpful about the system I'm running - it's just a standard windows 10 installation with python3.8 installed from python.org.

**Comment by ObaraEmmanuel** [comment]
The installation seems broken majorly because i forgot to add new packages to the set up file. See PR #6 for more details. Could we do this quickly and publish the fix to pypi asap
