### ISSUE TITLE
[FEATURE] Tab index

### ISSUE THREAD

**Issue by mrx23dot** [ObaraEmmanuel/Formation#51]
I'm looking for setting the Tab-index in a simple way.

In RADs usually there is an attribute like tab_order=8,  tab_order=-1

This should not be connected to the order in xml.

some reference to do it:
https://stackoverflow.com/questions/6687108/how-to-set-the-tab-order-in-a-tkinter-application

**Comment by ObaraEmmanuel** [comment]
That would involve changing the signature of the `ttk.Notebook` which is out of the scope of this framework. Addition of custom/special attributes can be done using custom widgets.

**Comment by ObaraEmmanuel** [comment]
I will try to add a way to easily change the ordering on the studio by altering the stacking order but I cannot add the attribute.

**Comment by ObaraEmmanuel** [comment]
You mean like dragging the items from the tree? That is difficult to implement in a controlled fashion but maybe in future. I will add stuff to the context menu to reposition tabs.

**Comment by ObaraEmmanuel** [comment]
Yeah, that can be added.

**Comment by ObaraEmmanuel** [comment]
Fixed.
